Support more chars in refs
knatten/cppquiz pull request #353
Opened 2024-08-25 09:21 UTC by tocic

Fixes https://github.com/knatten/cppquiz/issues/344.

2024-09-14 15:37 UTC, knatten requested changes
Sorry, I forgot to submit this review after adding the comments some weeks ago :(

2024-09-15 06:36 UTC, tocic commented on quiz/templatetags/quiz_extras.py
> +                [^\s*]*           # any number of non-whitespace characters except * (to support italicized links)
Hmm, are you sure? I've tested on a local server again:

![image](https://github.com/user-attachments/assets/df26de82-eda0-4f27-a0cf-40a0c1731972)
![image](https://github.com/user-attachments/assets/fd4a5c8a-cf82-49a9-8418-e755c1da4a3b)

The following commands
```
pip show markdown
pip show pymdown-extensions
```
output:
```
Name: Markdown
Version: 3.6
Name: pymdown-extensions
Version: 10.9
```

2024-09-15 09:16 UTC, knatten commented on quiz/templatetags/quiz_extras.py
> +                [^\s*]*           # any number of non-whitespace characters except * (to support italicized links)
Oh, my mistake, they both mean italic. Sorry about that.

2024-09-15 09:19 UTC, knatten approved these changes
Nicely done, thanks a lot! Please rebase on master, then I can merge it.

2024-09-16 19:46 UTC, merged

2024-09-16 19:47 UTC, knatten commented
And it's deployed! Thanks for fixing this.